services:
  website:
    command: env PATH="${ALEXANDRITE_REPOSITORY:-../repos/purescript-alexandrite}/target/release:$PATH" pnpm dev
    health: /playground
    portal:
      title: Website
    portals:
      - url: /playground
        title: Playground
